# Generated by Django 3.2.3 on 2021-07-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.ManyToManyField(to='apps.Listing'),
        ),
    ]
