# Generated by Django 3.2.3 on 2021-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, default='wrench', max_length=100, null=True),
        ),
    ]
